source 'https://github.com/CocoaPods/Specs.git'

platform :tvos, '10.0'
use_frameworks!

target 'Example' do
  pod 'FocusTvButton', :path => '..'
end

target 'ExampleTests' do
  pod 'FocusTvButton', :path => '..'
  pod 'Snap.swift', :git => 'https://github.com/dcordero/Snap.swift', :branch => 'tvOS'
end
