name: CI

on: ["push", "workflow_dispatch"]

jobs:
  test:
    runs-on: macOS-latest

    strategy:
      matrix:
        simulator: ['Apple TV', 'Apple TV 4K (3nd generation)']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install dependencies
        run: bundle install && bundle exec pod install --project-directory=FocusTvButton/

      - name: Linter
        run: ./FocusTvButton/Pods/SwiftLint/swiftlint
        
      - name: Test
        run: |
          xcodebuild test \
            -workspace FocusTvButton.xcworkspace \
            -scheme FocusTvButton \
            -destination "platform=tvOS Simulator,name=${{ matrix.simulator }}"

  swiftpm-test:
    runs-on: macOS-latest

    strategy:
      matrix:
        simulator: ['Apple TV', 'Apple TV 4K (3nd generation)']

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: update FB_REFERENCE_IMAGE_DIR and IMAGE_DIFF_DIR
        run: |
          swift scripts/updateTestPlan.swift

      - name: Build and test SwiftPM
        run: |
          swift package resolve
          xcodebuild test \
            -scheme FocusTvButtonSPM \
            -destination "platform=tvOS Simulator,name=${{ matrix.simulator }}"
