name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: macOS-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Bundler
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6

      - name: Install depencies
        run: bundle install && bundle exec pod install --project-directory=FocusTvButton/

      - name: Linter
        run: ./FocusTvButton/Pods/SwiftLint/swiftlint
        
      - name: Test
        run: xcodebuild test -workspace FocusTvButton/FocusTvButton.xcworkspace -scheme FocusTvButton -destination "platform=tvOS Simulator,name=Apple TV,OS=16.1"

